config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/search'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rental.rb
class Rental
  include ActiveModel::Validations
  include ActiveModel::Model
  attr_accessor :location, :price, :lat, :lng, :result
  validates :location, :price, :lat, :lng, presence: true


  def bnb_evaluate
    begin
      # cookie needed to get result in USD
      cookie = Rails.application.secrets.bnb_cookie
      url = "https://www.airbnb.com/wmpw_data?page=slash_host&duration=1_month&person_capacity=1&room_type=entire_home_apt&loading=false&sw_lat=#{self.lat}&sw_lng=#{self.lng}&ne_lat=#{self.lat}&ne_lng=#{self.lng}"
      http_result =  HTTP.headers("accept" => "application/json", "accept-language" => "en-US,en;q=0.8,cs;q=0.6").cookies(:session_cookie => cookie).get(url)
      json_result = JSON.parse(http_result)
      # "earning_estimation_duration":"1_week" is wrong their api response setting &duration=1_month just works
      diff = self.price.to_f - json_result["data"]["average_income_raw"].to_f
      if(diff > 0)
        self.result = "Rental through AirBnB is not worth. #{diff.abs.round(2)} USD less per month"
      elsif(diff < 0)
        self.result = "Think about renting through AirBnB you could make #{diff.abs.round(2)} USD more per month"
      else
        self.result = "Rental through AirBnB is the equal"
      end
    rescue StandardError => e
      self.errors.add(:base, "Problem with AirBnB evaluation")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @rental = Rental.new
  end

  def search
    @rental = Rental.new(rental_params)
     
    if @rental.valid?
      @rental.bnb_evaluate
    end
    
    render 'index'

  end
 
  private
  
  def rental_params
    params.require(:rental).permit(:location, :price, :lat, :lng)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= form_for @rental, url: home_search_path(), method: :get do |f| %>
	<%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :price, "Price (USD)" %>
  <%= f.number_field :price, min: 0, step: 0.1 %>

  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>

  <%= f.submit "Search", id: "submit" %>


  <p>
	  <% if @rental.errors.any? %>
	    <div id="error_explanation">
	      <ul>
	        <% @rental.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	  <% elsif @rental.result %>
	  	<p>Success</p>
	  	<%= @rental.result %>
	  <% end %>

  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Josef</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLp3mX2f-PTjzVMf_C26Wa2R72AZll-OE&libraries=places&callback=initAutoComplete"
    async defer></script>
  </body>
  </head>

  <body>
    <%= yield %>
  </body>
</html>